# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

apart_rcpp <- function(signal, pen, nStates) {
    .Call(`_apartruptures_apart_rcpp`, signal, pen, nStates)
}

